version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: carrental-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrental
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "3307:3306"
  backend:
    build: ./backend
    container_name: carrental-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8087
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/carrental?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8087:8087"
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: carrental-frontend
    depends_on:
      - backend
    ports:
      - "3000:80" 
    restart: unless-stopped
    environment:

      VITE_API_BASE_URL: http://localhost:8087

volumes:
  mysql_data: {}
